version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8-fpm
    volumes:
      - ./code:/code
    networks:
      - db_net
  db:
    image: mysql
    platform: 'linux/x86_64'
    environment:
      - MYSQL_ROOT_PASSWORD=root 
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - db_net
  dbc:
    image: phpmyadmin/phpmyadmin
    # links:
    #   - "db"
    environment:
      - PMA_HOST=db
    ports:
      - "8081:80"
    networks:
      - db_net
networks:
  db_net:
